SELECT 
HISTORY_ID,
CAR_ID,
date_format(start_DATE, '%Y-%m-%d') as START_DATE,
date_format(END_DATE, '%Y-%m-%d') as END_DATE,
if(DATEDIFF(END_DATE , START_DATE) +1 >= 30, '장기 대여', '단기 대여')
as RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE >= '2022-09-01' AND START_DATE < '2022-10-01'
order by HISTORY_ID desc