SELECT
CAR_ID,
ROUND(AVG(Datediff(END_DATE, START_DATE)+1),1) 
as AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
group by CAR_ID
having AVG(Datediff(END_DATE, START_DATE)+1) >= 7
order by 2 desc, 1 desc
